# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (https://username.github.io) then use these settings:
url: "https://madhur96.github.io"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: GSoC-19 Blog

# Short description of your site
description: Google Summer of Code 2019

You can read the proposal [here](https://drive.google.com/file/d/1xNH1OpCIiGwvumC4i_lglL6nXVz7r1Sy/view)

#### *Abstract*

Sampling algorithms and volume computation of convex polytopes are very useful in many scientific fields and applications. The package [volesti](https://github.com/GeomScale/volume_approximation) is a C++ package with an R interface which provides three geometric random walks for sampling and two state-of-the-art methods for volume estimation for convex polytopes being the first package providing such a variety of options in geometric statistics. volesti currently scales to a few hundreds dimensions in contrast to other available R packages, as [geometry](https://cran.r-project.org/web/packages/geometry/index.html), or C++ package [VINCI](https://www.math.u-bordeaux.fr/~aenge/index.php?category=software&page=vinci) that both only scale typically up to 15-20 dimensions. Thus it could be an essential tool for a quite large number of scientific applications in convex analysis, economics, biology or statistics, that need fast volume approximation or sampling in high dimensions. However, the possibility to scale from a few hundred to a few thousand dimensions was considered as a very far-reaching goal for many years. The goal of this project is to provide the first ever implementations for sampling and volume computation for convex polytopes in a few thousand dimensions. We exploit some very recent theoretical results that guarantee fast convergence and numerical stability in order to propose an efficient implementation of the current state-of-the-art geometrical random walks, i.e. Hamiltonian Monte Carlo and Vaidya walk. The proposed implementations will be a decisive contribution to other scientific fields as computational geometry, finance and optimization. We hope this project will be a decisive contribution towards the first complete and efficient tool for sampling, volume estimation and geometrical statistics in general and thus, help educational programs, research or even serve as a building block towards an international, interdisciplinary community in geometrical statistics.

#### *Bonding period*

* ##### *1st week*  
I have created [4 Pull Requests](https://github.com/GeomScale/volume_approximation/pulls) in github repository of `volesti` package, to add the implementations of my preliminary work for the GSoC proposal:  
1. [Check if the requested error is positive](https://github.com/GeomScale/volume_approximation/pull/14).
2. [Dikin walk implementation](https://github.com/GeomScale/volume_approximation/pull/16).
3. [Boundary sampling](https://github.com/GeomScale/volume_approximation/pull/15) with Hit-and-Run.
4. [Volume computation and sampling for low dimensional convex polytopes](https://github.com/GeomScale/volume_approximation/pull/17).

* ##### *2nd - 3rd week*
I have read some papers that are retated to the coding project. In particular, we discussed methods given in:  
1. [Algorithmic Theory of ODEs and Sampling from Well-conditioned Logconcave Densities](https://arxiv.org/abs/1812.06243), Yin Tat Lee, Zhao Song, Santosh S. Vempala.  
2. [Optimal Convergence Rate of Hamiltonian Monte Carlo for Strongly Logconcave Distributions](https://arxiv.org/abs/1905.02313), Zongchen Chen, Santosh S. Vempala.  
3. [The Dynamics of Lagrange and Hamilton](https://nisheethvishnoi.files.wordpress.com/2018/09/lagrangehamiltonian.pdf), Nisheeth K. Vishnoi.  
4. [Nonconvex sampling with the Metropolis-adjusted Langevin algorithm](https://arxiv.org/abs/1902.08452), Oren Mangoubi, Nisheeth K. Vishnoi.  
5. [Efficient Convex Optimization with Membership Oracles](https://arxiv.org/abs/1706.07357), Yin Tat Lee, Aaron Sidford, Santosh S. Vempala.  
6. [Riemann Manifold Langevin and Hamiltonian Monte Carlo](https://pdfs.semanticscholar.org/16c5/06c5bb253f7528ddcc80c72673fabf584f32.pdf), Mark Girolami, Ben Calderhead, Siu A. Chin.  
   
#### *Coding period*  

* ##### *1st week*  
I have created a [new branch](https://github.com/TolisChal/volume_approximation/tree/HMC_sampling) in my repo at github to implement Remannian Hamiltonian Monte Carlo. I have started coding.

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
    - GitHub Pages: "https://pages.github.com/"
# Author's home: "http://deanattali.com"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/img/xsf.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# --- Background colour/image options --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

# navbar-img: "/img/bgimage.png"
# footer-img: "/img/bgimage.png"
# page-img: "/img/bgimage.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Madhur Garg

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  rss: true
  email: "madhurgarg96@gmail.com"
  facebook: madhur.garg.3388
  github: madhur96
#  twitter: daattali
#  reddit: yourname
#  google-plus: +DeanAttali
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname

# Select which share links to show in posts
share-links-active:
#   twitter: true
  facebook: true
  google: false
#   linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "madhur96.com"  # eg. "deanattali.com/beautiful-jekyll"

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.

#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Comments --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
# disqus: ""

# If you want to use JustComments fill with the API Key
#just-comments: "ABCD-EFGH-IJKL"

# To use Facebook Comments, fill in a Facebook App ID
# fb_comment_id: ""

# Staticman support
staticman:
  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
  branch     : # eg. "master" If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
  endpoint   : # URL of your own deployment (with trailing slash) (will fallback to a public GitLab instance)
  reCaptcha:
    # reCaptcha for Staticman (OPTIONAL)
    # If you use reCaptcha, you must also set these parameters in staticman.yml
    siteKey  : # Use your own site key, you need to apply for one on Google
    secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>

# --- Misc --- #

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "India"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags index page and make tags on each post clickable
link-tags: true

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
